server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: bellatrix-auth
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/orion_auth}
    username: ${SPRING_DATASOURCE_USERNAME:orion}
    password: ${SPRING_DATASOURCE_PASSWORD:orion}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

springdoc:
  swagger-ui:
    path: /swagger-ui.html
